-module(problem2).
-export([main/0]).

%% Each new term in the Fibonacci sequence is generated by adding the
%% previous two terms. By starting with 1 and 2, the first 10 terms
%% will be:
%% 
%% 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
%% 
%% By considering the terms in the Fibonacci sequence whose values do
%% not exceed four million, find the sum of the even-valued terms.

solve(Max, Cur, Prev, Acc) ->
    if
        Cur > Max ->
            Acc;
        Cur rem 2 == 0 ->
            solve(Max, Cur + Prev, Cur, Acc+Cur);
        true ->
            solve(Max, Cur + Prev, Cur, Acc)
    end.

main() ->
    solve(4000000, 1, 1, 0).
